[package]
name = "bitwise_sort" 
version = "0.1.0"   
authors = ["Iotti <thi.iotti@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3